spring.datasource.url=jdbc:postgresql://localhost:5432/database
spring.datasource.username=postgres
spring.datasource.password=romaroma21roma

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect
server.port=4321

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=Ryskeldiosmonaliev54@gmail.com
spring.mail.password=Ryskeldi19971997
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=trued