package com.peaksoft.model.entity.enums;

public enum ComplaintsType {

    SPAM,
    VIOLENCE,
    MANIFESTATION_OF_HATRED,
    ILLEGAL_ACTIVITIES_OR_REGULATED_GOODS,
    CALLS_FOR_VIOLENCE_DANGEROUS_ACTIONS,
    SCENES_OF_A_PORNOGRAPHIC_NATURE,
    OTHER

}
